version: '3.8'

services:
  solr:
    image: solr:latest
    container_name: solr_container
    ports:
      - "8989:8989" 
python:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: python_container

    depends_on:
      - solr